name: .NET Migrator

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
    
defaults:
  run: 
    working-directory: ./Src

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore DeUrgenta.Domains.Migrator.sln

    - name: Build
      run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true DeUrgenta.Domains.Migrator.sln